### ISSUE TITLE
Provide 'how to upgrade' instructions, please?

### ISSUE THREAD

**Issue by luciansmith** [yaroslaff/evalidate#5]
I'm trying to maintain legacy code, which literally just broke because evalidate.evalidate is now gone.  I don't know the code nearly well enough to tell how to update it; some sort of 'if you did X, do Y now' instructions would be fantastic.

Specifically, the code in question looks like:

```python
    math_node = evalidate.evalidate(math,
                                    addnodes=VALID_MATH_EXPRESSION_NODES,
                                    funcs=MATHEMATICAL_FUNCTIONS.keys())
    compiled_math = compile(math_node, '<math>', 'eval')
    return compiled_math
```

Any hints appreciated!

**Comment by yaroslaff** [comment]
Easiest workaround is just  to lock evalidate version to any before 2.0.0 (which I published just few hours ago), e.g. v1.1.0 has evalidate function.

But better to upgrade it:
~~~python
#!/usr/bin/env python3

import evalidate

VALID_MATH_EXPRESSION_NODES = ['Call', 'Mult']
MATHEMATICAL_FUNCTIONS = ['int']

def prepare(math):
    model = evalidate.base_eval_model.clone()
    model.nodes.extend(VALID_MATH_EXPRESSION_NODES)
    model.allowed_functions.extend(MATHEMATICAL_FUNCTIONS)

    expr = evalidate.Expr(math, model=model)
    return expr.code

code = prepare('int(a) * 3')

# 36
print(eval(code, None, dict(a=12.34)))
~~~

**Comment by luciansmith** [comment]
Thank you!  That was enough to figure it out, though I did have to change 'expr.code' to 'expr.node' to match the previous functionality.  For future explorers:

```python
    math_node = evalidate.evalidate(math,
                                    addnodes=VALID_MATH_EXPRESSION_NODES,
                                    funcs=MATHEMATICAL_FUNCTIONS.keys())
```

becomes:

```python
    model = evalidate.base_eval_model.clone()
    model.nodes.extend(VALID_MATH_EXPRESSION_NODES)
    model.allowed_functions.extend(MATHEMATICAL_FUNCTIONS.keys())

    math_node = evalidate.Expr(math, model=model).node
```

If something like this could be added to the docs (for this and other functionality), I think that would help anyone else in the same boat.

**Comment by yaroslaff** [comment]
Attribute `node` is parsed AST tree, but not an python byte-code. Do you really need it (AST-tree)? If you need to eval(), then Expr.code is byte-code which would be evaluated very quickly (no need to call compile() to convert AST node to bytecode). Using `code` attribute can speed-up execution greatly (as demonstrated in benchmarks).

**Comment by luciansmith** [comment]
It's possible the downstream code could also be changed, but since 'evalidate' retuned a node, that's what the code expects--using 'code' gave me an error it took some time to track down.  This is not time-sensitive code; the time it takes me as a programmer to update stuff is far far longer than the time spent executing it.
