### ISSUE TITLE
Version 2.0.0 is not working for python 3.8

### ISSUE THREAD

**Issue by karthikkalasani** [yaroslaff/evalidate#6]
I noticed this error when running with python 3.8. The Type Hinting Generics in Standard Collections is supported only in python 3.9 or above

**TypeError: 'type' object is not subscriptable**

**Comment by yaroslaff** [comment]
Fixed in 2.0.1, now tested on Python 3.7 on Debian Buster. Please confirm it's working for you :-).

**Comment by yaroslaff** [comment]
I think version 2.0.1 is working with Python 3.7 (at least works for me). Reopen ticket if you have any problems with it.
